<a href="https://colab.research.google.com/github/sadhiin/100-class-image-classifiaction/blob/main/02_Gradient_calculation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([0.3615, 1.5739, 0.9097], requires_grad=True)


In [8]:
y = x + 2
print("y: ", y)

z = y*y*2
z = z.mean()
print("z:",z)
z.backward()  # calculating gradients
print("x:", x.grad)

y:  tensor([2.3615, 3.5739, 2.9097], grad_fn=<AddBackward0>)
z: tensor(17.8770, grad_fn=<MeanBackward0>)
x: tensor([12.5947, 19.0608, 15.5181])


In [14]:
z = y*x*2
# z = z.mean()
print("z:",z)
v = torch.tensor([0.1, 0.8, 0.1], dtype=torch.float32)
z.backward(v)
print("x grad:", x.grad)

z: tensor([ 1.7074, 11.2499,  5.2935], grad_fn=<MulBackward0>)
x grad: tensor([15.5731, 58.4066, 19.3736])


In [15]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([ 0.8583,  1.4368, -0.5261], requires_grad=True)


In [16]:
# x.requires_grad_(False)
# x.detach() # this will create a new tensor that doesn't requird gradient
# with torch.no_grad():

In [18]:
x.requires_grad_(False)
print(x)

tensor([ 0.8583,  1.4368, -0.5261])


In [21]:
x = torch.rand(3, requires_grad=True)
print("X:",x)
y = x.detach()
print('Y:', y)

X: tensor([0.3986, 0.4943, 0.4591], requires_grad=True)
Y: tensor([0.3986, 0.4943, 0.4591])


In [22]:
x = torch.rand(3, requires_grad=True)
print("x: ", x)
with torch.no_grad():
  y = x+2
  print("Y: ",y)

x:  tensor([0.1141, 0.9899, 0.0664], requires_grad=True)
Y:  tensor([2.1141, 2.9899, 2.0664])


### Carefull

In [24]:
weights = torch.ones(4, requires_grad=True)
for epoch in range(3):
  model_output = (weights*3).sum()
  model_output.backward()
  print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [25]:
weights = torch.ones(4, requires_grad=True)
for epoch in range(3):
  model_output = (weights*3).sum()
  model_output.backward()
  print(weights.grad)
  weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
